import type { Metadata } from "next";
import { Kumbh_Sans } from "next/font/google";
import "./globals.css"
import Header from '@/components/Header'

const inter = Kumbh_Sans({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#f2f2f2]`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
